import Link from 'next/link'
import './globals.css'
import { Control } from './Control';

export const metadata = {
  title: "Web Tutorials",
  description: "Generated by jiyeon",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', { next: { revalidate: 0 } });
  const topics = await resp.json();

  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {topics.map((topic)=>{
            return <li key={topic.id}>{topic.id}. <Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
